### ISSUE TITLE
bower version 0.2.3

### ISSUE THREAD

**Issue by alxdnlnko** [hakib/MassAutocomplete#24]
Hi. When would the 0.2.3 version be published in bower? I'm stil waiting for my commits in production, don't want to install it from my fork.

Btw, you didn't fix the version in bower.json.

**Comment by hakib** [comment]
Hey @Alex, ill get to it as soon as possible.
בתאריך 20 במרץ 2015 02:08, "Alex Danilenko" <notifications@github.com> כתב:

**Comment by hakib** [comment]
Bumped version. Try it now.

**Comment by alxdnlnko** [comment]
.min version still doesn't have `preventDefault()`. Did you forgot to rebuild?

**Comment by hakib** [comment]
Very odd. Regenerated.

**Comment by alxdnlnko** [comment]
Thanks :+1:

**Comment by alxdnlnko** [comment]
When installing 0.2.3 from bower, there is no `preventDefault()` yet...

**Comment by hakib** [comment]
Hey Alex, Make sure you don't you fetch the package from the cache. 
I just `bower install`ed and it included the fix.

**Comment by alxdnlnko** [comment]
I've installed in on a new server today. No preventDefault on enter button. Had to install it from my fork again... :(
