### ISSUE TITLE
Example on pluncker

### ISSUE THREAD

**Issue by fipartners** [hakib/MassAutocomplete#25]
I have made a plunker for remote example for help

http://plnkr.co/edit/vTnxfF5hz3w74V5SMY7q?p=preview

**Comment by hakib** [comment]
Hey man, 
Not sure exactly what is the problem you are refereeing to here but i can see that this is clunky so i've edited your plunker with several modification

1. Starting at 0.2.3 i've added a smooth transition between suggestions cycles. Meaning the suggestion box will not disappear while the directive is waiting for results. I changed the import to use the latest MassAutocomplete version from rawgithub.
2. Your resource is very slow. I suggest adding a simple cache. I've implemented a simple cache based on the first latter of the term. You can see now that when searching for more then one latter the cache is being used (This is under the assumption that you implement a simple startsWith matching in the server side as well). 

You can check out my modified version here: 

http://plnkr.co/edit/AC4HjHx9yj2SGqwgkbUD?p=preview

**Comment by fipartners** [comment]
Hi

Thanks, my plunker was just for help others because I am not familiar with promise.
