### ISSUE TITLE
Uncaught TypeError: m.suggest is not a function

### ISSUE THREAD

**Issue by alarrosa14** [hakib/MassAutocomplete#28]
Getting `Uncaught TypeError: m.suggest is not a function` when starting to type.

```
<div mass-autocomplete>
   <input class="form-control"  ng-model="client"  mass-autocomplete-item="client_names">
</div>  
```

Angular: v1.3.15

**Comment by hakib** [comment]
Whats the object `client_names` ? 
If it's just a list of clients then it wont work. `client_names` should be an object with at least a `suggest` function. 

Check out the examples [here](http://hakib.github.io/MassAutocomplete/#examples)
