### ISSUE TITLE
'Suggest' function not triggered 

### ISSUE THREAD

**Issue by byounathan** [hakib/MassAutocomplete#29]
Using your examples (http://hakib.github.io/MassAutocomplete/#examples), if input field is selected and you immediately paste a 'valid' value from your clipboard, the suggest function is not triggered. In result, the suggestion popup doesn't appear.

For example;
1. copy 'Alabama' to your clipboard
2. go to first example (i.e. suggest state).
3. focus on the input field and immediately paste the value from your clipboard.

Actual Result: nothing happens.
Expected Result: suggestion popup to appear with one item (i.e. 'Alabama').

Note: if you undo (ctrl+z) and re-paste (ctrl+z), the suggestion popup appears as expected. The issue is appears to be related to the initial focus event.

This has been reproduced in Chrome (v 40.0.2214.115 m) & Firefox (v 37.0.2)

**Comment by hakib** [comment]
Hey @byounathan, this behavior is actually expected. 

There is a delay between the time you focus the field until it is attached (and ready to provide suggestion). To illustrate I suggest going through the same scenario only this time do it in the first example on the page where the events are shows. You will see that when you quickly paste the data the attach event is lagging slightly behind. The reason for that is that attach is relatively expansive (positioning the suggestions box) so we want to reduce the amount of trash behind the scenes. The scenario I has in mind is of a user quickly jumping through the form fields using the TAB key.

Gladly, you can control this behavior using the `debounce_attach` argument. You can read all about it in the [options section]( http://hakib.github.io/MassAutocomplete/#options).

Hope this helps, 
Haki.
