### ISSUE TITLE
angular-mass-autocomplete with http request

### ISSUE THREAD

**Issue by jbarros35** [hakib/MassAutocomplete#31]
I dont know how to make this code works properly

'home.controller('categoryController', function ($scope, $http, $sce, $q) {

		//var states = ['Alabama', 'Alaska', 'California', 'New york'];

		function suggest_state(term) {
			var q = term.toLowerCase().trim();
			var results = [];
			$http.get('/api/posts/findTags?name='+q).success(function(res){
				for (var i = 0; i < res.length && res.length < 10; i++) {
					results.push({ label: res[i].description, value: res[i].description });
				}
				return results;
			}).error(function(err){
				console.log(err);
			});

			return results;
		}

		function suggest_state_delimited(term) {
			var ix = term.lastIndexOf(','),
				lhs = term.substring(0, ix + 1),
				rhs = term.substring(ix + 1),
				suggestions = suggest_state(rhs);

			suggestions.forEach(function (s) {
				s.value = lhs + s.value;
			});

			return suggestions;
		};

		$scope.ac_option_delimited = {
			suggest: suggest_state_delimited
		};
	});'

can you help me how to make it wait until loading data from the http get? it returns always before getting data...

thank you.

**Comment by hakib** [comment]
Hey @jbarros35, 
Take a look at the example in [this issue](https://github.com/hakib/MassAutocomplete/issues/25). When fetching from a remote data the suggest function should return a promise.
