### ISSUE TITLE
3 Letter minimum

### ISSUE THREAD

**Issue by SkyByteStudio** [hakib/MassAutocomplete#32]
Hello,

Would you be able to implement a minimum 3 letter parameter before rendering results please,

Thanks,

**Comment by hakib** [comment]
Hey @SkyByteStudio, 

If you want to make suggestions only for inputs greater than 3 letters you need to have your suggest function return an empty array for short terms. Check out the `suggest_state_with_highlight` in the [highlight examaple](http://hakib.github.io/MassAutocomplete/#examples) - the suggestion box appear only if the input greater than 2 letters.

Let me know if you need any more help, 
Haki.

**Comment by SkyByteStudio** [comment]
Thank you Haki, that worked!

**Comment by hakib** [comment]
Great !
