### ISSUE TITLE
Clear model passing objects

### ISSUE THREAD

**Issue by mraffo** [hakib/MassAutocomplete#33]
I have this code:

$scope.autocompleteOptions = {
	suggest: $scope.suggestContacts,
	on_select: $scope.addContactToGuests
};

$scope.addContactToGuests = function(selected) {
	$rootScope.contacts.push(selected.contact);
	$scope.contact = undefined;
};

But the input wasnt cleaned before de selection. In the example page of MassAutocomplete, it works similary.

Whats wrong? Help me please.

**Comment by hakib** [comment]
Make sure you set your input to `ng-model=contact`

**Comment by mraffo** [comment]
Yes, it is setted. Check <input type="text" class="form-control" mass-autocomplete-item="autocompleteOptions" ng-model="contact"/>

**Comment by mraffo** [comment]
Any Answer? could you see the problem?

**Comment by hakib** [comment]
Hard to tell from these bits of code. Can you set up a plunker / fiddle / jsbin to demostrate the probelm ? This dosent seem like an issue with the directive, it looks like something in you code.
