### ISSUE TITLE
ng-model receive value of the input field even if empty

### ISSUE THREAD

**Issue by karlkurzer** [hakib/MassAutocomplete#34]
Dear @hakib,

first of all thanks for this great directive and the variety of options for its configuration.
**Great job!**

My goal is to bind the value of the input to a $scope.variable however it is not binding. My workaround as of now is to assign the *term* to a $scope.variable when fuzzy_suggest gets called

```javascript
function fuzzy_suggest(term) {
            if (!term) {
                // filter assignment
                $scope.searchText = '';
                return [];
            }
            // filter assignment
            $scope.searchText = term;
```
this however only gets called as long as there is at least one character in the input field - not when the input is empty *line 128*.

```javascript
function _suggest(term, target_element) {
        $scope.selected_index = 0;
        $scope.waiting_for_suggestion = true;
        if (typeof(term) === 'string' && term.length > 0) {
```

I am sure that I am missing something and would thus be grateful for a quick hint, what I can do to always extract the value of the input `{{input}}`

Thanks a lot.

Best,
Karl

**Comment by hakib** [comment]
Hey @karlkurzer, 

I'm not sure I understand what you mean by "bind the value of the input to a $scope.variable" but if your objective is to manipulate / show the value which is currently in the input then you can use the variable you bound to the `ng-model`.

See [this example](http://plnkr.co/edit/AC4HjHx9yj2SGqwgkbUD?p=preview). You can see that `{{dirty.value}}` is used by the `ng-model` and is also used in the template.

**Comment by karlkurzer** [comment]
Hey @hakib 

thank you for your quick answer, the plunker and my code work now.

What i tried was:

```javascript
$scope.search = ''
```
```html
<div mass-autocomplete>
<input ng-model="search" mass-autocomplete-item="ac_fuse_options">
</div>
```
instead of

```javascript
$scope.search = {value:''}
```

```html
<div mass-autocomplete>
<input ng-model="search.value" mass-autocomplete-item="ac_fuse_options">
</div>
```
I guess it needs to be an object...

Thanks,
Karl
