### ISSUE TITLE
Installation via npm

### ISSUE THREAD

**Issue by MartyIX** [hakib/MassAutocomplete#38]
Hi,

can I install the plugin via npm? We try to move from Bower to npm and it seems that MassAutocomplete is not registered in npm registry.

Publishing a package should be quite straightforward: https://gist.github.com/coolaj86/1318304

What do you think about this suggestion?

Have a nice day,
Martin

______
http://gofore.com/ohjelmistokehitys/stop-using-bower/

**Comment by hakib** [comment]
Sounds like a good idea !

**Comment by MartyIX** [comment]
:+1: It should only take a minute, if I understand the process correcly :-)

**Comment by hakib** [comment]
You can now install massautocomplete from npm using 

```
npm install angular-mass-autocomplete
```

Thanks @MartyIX for making me do this.

**Comment by MartyIX** [comment]
Thanks!
