### ISSUE TITLE
Feature request: configurable undo using escape key

### ISSUE THREAD

**Issue by kazupooot** [hakib/MassAutocomplete#41]

**Comment by hakib** [comment]
Hey @kazupooot, I'm not sure I understand what you mean. Do you mean being able to configure the button that cancel the selection or being able to configure what will happen when pressing ESC?

**Comment by kazupooot** [comment]
Sorry about that. Yep, being able to configure what will happen when pressing esc. For example, when pressing the ESC, it should not undo changes. :)

Btw, great autocomplete! :)

**Comment by hakib** [comment]
So it's more like being able to configure which keys will be active.

I'm a bit swamped at the moment so if you want to set up a PR that will be great.

**Comment by kazupooot** [comment]
Sure. Will try to make one. Thanks!
