### ISSUE TITLE
Capture the input ng-model when pressing enter

### ISSUE THREAD

**Issue by bwyss** [hakib/MassAutocomplete#45]
Love the directive btw.

I would like to be able to capture the input ng-model when the user simply enters a value and presses enter and has not selected a filed from the autocomplete list. Is this possible with the MassAutocomplete API?

**Comment by hakib** [comment]
Hey @bwyss, Thanks. 

`ng-model` is not disturbed so you should be able to watch it. As to the Enter key, the directive will stop propagation only if it handled the event (meaning, the user had focus on a selection and pressed enter).  I believe you should be able to capture Enter when the user does not have a selected option.

Haki.
