### ISSUE TITLE
Prevent suggestion cycle when the value is the last value selected should be optional

### ISSUE THREAD

**Issue by amaalej** [hakib/MassAutocomplete#46]
I am facing a situation where:
1 - I need to refind the already selected value (because I can remove the selection outside the MassAutocomplete component)
What is blocking me is: Line 113
```
if (nv === last_selected_value)
    return;
```
I reset my ng-model to "", but the watcher is not triggered.
Is it possible to make it optional?
Thank you very much

**Comment by hakib** [comment]
Hey @amaalej, 

This row was meant to prevent unnecessary suggestion cycles when the value is not changing. The only reason I can think of for this to pose a problem is if the suggestions them self's change (lets say, by using a live feed from the server with constantly updating suggestions).

If this is the case then the problem you should have, if I understand the use case, is how to trigger a suggestion cycle in the AC directive.... is that correct? It it possible for the user to enter "X" get 2 suggestions and a seconds later get 2 more suggestions for "X"?

I see a lot of questions / PR's around this line so i'm trying to understand better what all if this issues have in common.

**Comment by amaalej** [comment]
Dear Haki, 
Thanks for your response.
Actually the component should not have such an intelligence level, in other terms, it shouldn't keep in memory -by default- the already chosen item.

Having such a memory should be optional.

My use case is: I use MassAutocomplete to search generate filters:
1 - I type "X", I have 3 choices ["xenon", "box", "boxing"]
2 - I select "box" as a filter for my app,
3 - I remove my filter, (no more filters exist in my application)
4 - I type "X", I have only 2 choices ["xenon", "boxing"] without "box"

Is there any solution to reset the component, or to remove the memorized value.

Cordially

**Comment by hakib** [comment]
> Actually the component should not have such an intelligence level

This directive is mostly focused on performance so it makes sense for it to not trigger an expensive suggestion cycle if the value does not change.

Lets break down your use case form the directive point of view

> 1 - I type "X", I have 3 choices ["xenon", "box", "boxing"]

AC triggered `on_suggest` and you returned three suggestions.

> 2 - I select "box" as a filter for my app,

AC triggered `on_select`, the `last_selected_value` is now "box", the suggestion box does not appear on the screen.

> 3 - I remove my filter, (no more filters exist in my application)

You did some change external to the AC directive.

> 4 - I type "X", I have only 2 choices ["xenon", "boxing"] without "box"

You type "X", model value watch is triggered -> the new model value (nv) is "X", the `last_selected_value` is `box` -> they are not equal -> `on_suggest` is triggered -> you can return `["xenon", "boxing"]`.

One situation I think might required some action from your part is if at step 4 you retype `box` (_quickly enough for the debounce to only catch the complete term `box`_). In this case the `nv` is `box` and the last value is also `box` so a suggestion cycle will not trigger.

The directive is watching the model value so you can overcome that by setting the model value in your controller/factory on `on_select`. This way you can "reset" the directive. I actually have an example of this in the gh-page
