### ISSUE TITLE
on_detach is not working

### ISSUE THREAD

**Issue by udayky372** [hakib/MassAutocomplete#48]
This is my code

<div id="search_filters_container"  >
            <div mass-autocomplete">
                Assigned to
                <input id="search_filter_coach_select" type="text" ng-model="AssignedTo" mass-autocomplete-item="coach_results">
            </div>

  this.$scope.coach_results = {
            suggest: this.getCoachesList.bind(this),

            on_select (selected) {
                this.$scope.coach = selected.userId;
            },
            on_detach (selected) {
                this.$scope.coach = selected.userId; 
            }
        }
    }

So the problem now I am facing is,

If I select item from suggestion box this.$scope.coach  is filled with a value (selected.userId), but I clear the text box manually then the scope item is not getting cleared (having null or " "), so I used on_detach method but on blur it's not hitting the method.

**Comment by hakib** [comment]
How are you making sure that on_detach is not being called?

Note also that on_detach is invoked with the current model value (text) and not the item (object in your case).

**Comment by udayky372** [comment]
Agreed, the thing that I implemented now is, if I enter a letter (or letters) in textbox mass autocomplete will give some suggestions (my each suggestion contain value--> stores in ng-model, label -->  for visibility). So if I select 'a suggestion', on_select will be triggered, during that time I am assigning the value to $scope property (value: selected.userId;) as above in on_select method. 

Now the thing is if I clear the value in text box that means I am not selecting anything from suggestion box, so on_select won't be fired so the previous value in $scope.coach will remain same but i don't want that. 

If clear my text box, the value in $scope should also be cleared. That's why I used on_detach but It's not triggered after clear text box and blur the text box.

 <div id="search_filters_container" ng-show="MemberSearchResultsCntrl.collapsed" ng-hide="!MemberSearchResultsCntrl.collapsed">
            <div mass-autocomplete="{debounce_suggest:100, debounce_blur:100000}">
                Assigned to
                <input id="search_filter_coach_select" type="text" ng-model="AssignedTo" mass-autocomplete-item="coach_results">
            </div>

**Comment by hakib** [comment]
on detach is invoked when you blur the text box. So, as you figures out already, if you deleted the text in the input it *will not* detach and that is expected behavior.

If you blur the field on_detach should be called with the text currently in box. You can see the first example on the website that demonstrate the callbacks. If you focus the field and then blur you will have two callbacks - attach and detach.

Can you run [the example](https://github.com/hakib/MassAutocomplete/blob/gh-pages/index.js#L42) and make sure the on_detach is not invoked or maybe set up a jsbin with an example to demonstrate your issue?

**Comment by udayky372** [comment]
Okay, now I found the issue, on_detach() is not working properly on blur if I have  mass-autocomplete="{debounce_blur:200}" in div tag. 

If I remove debounce_blur, then on_detach working properly on blur. 

But I want debounce_blur because on select user click on the suggestion item for while, so if I don't have this then the selected item not coming in text area (instead the entered letters will stay in the text box). 

Is there any solution to fix the issue?

**Comment by udayky372** [comment]
Problem got solved, decreased the debounce_blur time to 500ms, so it will get call the on_detach in 500ms. Thanks though.
