### ISSUE TITLE
clear input if no match found

### ISSUE THREAD

**Issue by victorng123** [hakib/MassAutocomplete#49]
Could you give me some idea how to clear the user input if no match with the results.
I want force user to select from the results list.

Thanks in advance.

Victor

**Comment by hakib** [comment]
If what you need is a select box with auto complete then respond only to `on_select`.

If for example the user pressed enter with no selected value you can catch it and handle any way you see feat. For example, you can show a message indicating he should select from the list.

**Comment by victorng123** [comment]
not from select box but textbox.

if user key in "united k"
and the list is showing "United Kingdom", user skip to select from the list but leave the textbox as "united k", i'm thinking is there any easily way for me to remove the text after user proceed to enter for next field.

**Comment by hakib** [comment]
I think what you are looking for is similar to the "tags" example. Check out the example code under "_Using the selected object_" [here](http://hakib.github.io/MassAutocomplete/)
