### ISSUE TITLE
Hiding autocomplete when using a remote source and nothing has been selected.

### ISSUE THREAD

**Issue by ashleahhill** [hakib/MassAutocomplete#5]
I ran into this using a remote source, you can see the same behavior on the [Remote source](http://hakib.github.io/MassAutocomplete/) example.

When the user puts a value in the field and then clears it (backspace, cut) the ng-model value updates but the autocomplete does not. It remains visible and populated.

![image](https://cloud.githubusercontent.com/assets/1854792/5345788/856031f0-7ee8-11e4-9ea4-07868b91b074.png)

I found that changing part of [the watch expression](https://github.com/hakib/MassAutocomplete/blob/master/massautocomplete.js#L113)

from 
````javascript
 if (nv === last_selected_value) 
    return;
````
to
````javascript
 if (nv === last_selected_value && nv !== undefined) 
    return;
````

Seemed to fix the issue, but I'm not confident in its place in the wider design of the plugin.

**Comment by hakib** [comment]
I am unable to reproduce this issue. I have made some changes to the way remote sources are being treated - If the issue is still not resolved, reopen please.

**Comment by thethakuri** [comment]
I wasted last hour trying to figure out why wouldn't my suggest box disappear when I clear out my input box. The problem was I set the required (for validation) attribute on my input which was being set as udefined and not '' after clearing out. What is workaround this ?
