### ISSUE TITLE
Feature Suggestion : Making the whole li element clickable

### ISSUE THREAD

**Issue by thethakuri** [hakib/MassAutocomplete#51]
I was having trouble selecting suggestion items when clicked outside the text. I think it is better if you make your whole 'li' element clickable by simply moving ng-click directive to li 

```
'<li ng-repeat="result in results" ng-if="$index > 0" ' +
      'class="ac-menu-item" ng-click="apply_selection($index)" ng-class="$index == selected_index ? \'ac-state-focus\': \'\'">' +
     '<span ng-bind-html="result.label"></span>' +
 '</li>'
```

Also, if the user types in the box but doesn't select from suggestions and the typed text matches with an item in suggestions, then we can force selection on blur.

**Comment by hakib** [comment]
Have you tried styling `.ac-item` to occupy 100% of the width? That should solve it.

**Comment by thethakuri** [comment]
Doesn't work for height.

**Comment by hakib** [comment]
@thethakuri If you look at the examples in the gh-page you will see that the entire row is clickable. This is a styling issue and if you have a problem occupying the entire height of the list element I can suggest using `padding:0` on the `li`.
