### ISSUE TITLE
event handlers attached to global Window object should use namespaces

### ISSUE THREAD

**Issue by mvberg** [hakib/MassAutocomplete#52]
Currently the directive will clear (detach) all 'resize' event handlers attached to the Window object when directive's scope is destroyed. 

Proposed fix to line 35:

```js
RESIZE: 'resize.massAutocomplete',
```

**Comment by hakib** [comment]
Hey @mvberg, I think it's a good idea. 

I remember I had prefixed the event back when I was using jquery but I dropped it when I moved to only using js (don't remember why but I'm pretty sure I had a reason).

Do you know of any browser support issue with prefixed events?

**Comment by hakib** [comment]
From [the jqLite docs](https://docs.angularjs.org/api/ng/function/angular.element): 

> on() - Does not support namespaces, selectors or eventData
