### ISSUE TITLE
Button on suggestion box template

### ISSUE THREAD

**Issue by isaacdustin** [hakib/MassAutocomplete#54]
Hi,

Is there a way to add a clickable button on the suggestion box? I tried to create one but everytime I click on it the box was closing. Really need your help on this one. Thanks!

**Comment by hakib** [comment]
Hey,

The AC container handles click event on an AC item as selection so it make sense it's closing the container.

Try calling `stopPropagation()` in your button click handler. It should prevent the AC container from getting the event.

**Comment by isaacdustin** [comment]
I did that already but still doesn't work the way that I want it. Anyway, thanks for your quick response. I will still continue to investigate on it. If you did something that could fix this issue please inform me immediately.

**Comment by isaacdustin** [comment]
I just found out that the real problem is that directives are not working on the suggestion box custom template. Please help. :)

**Comment by hakib** [comment]
Yeah, it makes sense... ng-bind-html evaluate expression it does not compile.

How about styling the element in the list and handle the click action in the on select handler raised by the AC directive? I'm not sure how compiling each element in he list will effect performance.

**Comment by isaacdustin** [comment]
Yeah, that works. Thanks for your time.:)
