### ISSUE TITLE
ng-model conflict?

### ISSUE THREAD

**Issue by guillaumegarcia13** [hakib/MassAutocomplete#62]
Hi,

Thanks for this project, really useful!

One quick question: I saw that you apply the ['dot rule'](http://jimhoskins.com/2012/12/14/nested-scopes-in-angularjs.html) in your examples and, indeed, when you have a _ng-model_ without a dot, MassAutocomplete seems to mess up with the binding.
Is this a known / fixable issue?

Thanks in advance.

**Comment by hakib** [comment]
Thanks @guillaumegarcia13, 

The directive uses angular's utilizes ng model built-in behavior so AFAIK there are not special issues with that. However, the 'dot rule' as you call it, is a matter of scope inheritance in angular and it's a pretty important one so you should focus on that. I must say I personally haven't encountered many situations when I *did not* bind an object to ngModel.
