### ISSUE TITLE
List all suggestions on focus

### ISSUE THREAD

**Issue by xialin** [hakib/MassAutocomplete#65]
Is it possible to list down suggestion list when user click on the field (before typing anything)?

**Comment by hakib** [comment]
Hey @xialin, sorry it took me a while, i'm a bit swamped at the moment.

There is no built in way of doing it (though I can understand the use case, especially for small lists). I guess you can try setting a model value `on_attach` and return all values in the initial `suggest` callback. I haven't tried it but it's worth a shot.

**Comment by Squishier** [comment]
> There is no built in way of doing it (though I can understand the use case, especially for small lists). I guess you can try setting a model value on_attach and return all values in the initial suggest callback. I haven't tried it but it's worth a shot.

I did exactly this. It works just fine.
