### ISSUE TITLE
It triggers a CSP error

### ISSUE THREAD

**Issue by thany** [hakib/MassAutocomplete#66]
When including MA on a page that has a fairly default content security policy (CSP) set, it triggers, because MA tries to inject a stylesheet into the page.

This is my CSP:
```html
  <meta http-equiv=Content-Security-Policy content="default-src 'self'; script-src 'self' https://ajax.googleapis.com">
```

And the error thrown because of MA:
```
13:55:40.528 Content Security Policy: The page's settings blocked the loading of a resource at self ("default-src http://192.168.178.39:3000"). Source: position:absolute;. 1 192.168.178.39:3000
```

A possible solution is to respect the presence of the `ng-csp` directive (and settings thereof). To get styles onto an element, you'd need to somehow provide (perhaps simply through documentation) a separate piece of stylesheet that developers have to include in their existing stylesheets.

**Comment by thany** [comment]
Here, have a PR 😎

**Comment by hakib** [comment]
Hey @thany, thanks for the PR. Looks simple enough, i'll take a look and merge.

The error message you are getting is a bit weird, I expected to see violation of `style-src unsafe-inline`...

**Comment by thany** [comment]
I don't have a `style-src` set, so my browser (Firefox) just reports the policy rule that it faults on. In this case, that's the `default-src`. If I did have a `style-src` set, I'm sure it would report on that.
