### ISSUE TITLE
Strange error after minifying

### ISSUE THREAD

**Issue by thany** [hakib/MassAutocomplete#69]
When I use MA, everything's fine. But when I pull it through my build script which includes minification, I get these strange errors with every keystroke:

```
Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 27-27 [\] in expression [$index == selected_index ? \'ac-state-focus\': \'\'].
http://errors.angularjs.org/1.6.2/$parse/lexerr?p0=Unexpected%20next"haracter%20&p1=s%2027-27%20%5B%5C%5D&p2=ndex%20%3D%3Delected_index%20%3F%20%5C'ac-state-focus%5C'%3A%20%5C'%5C'
```

Turns out something is going wrong with the escaped quotes in the directive template. I'm not sure if this is a problem in my minifier [babili](https://www.npmjs.com/package/babili), or an oversight in MA. But it can easily be fixed by putting the template in, well, a [template string](http://tc39wiki.calculist.org/es6/template-strings/) :)

I'll make a PR shortly.

**Comment by thany** [comment]
And there it is, as promised.

**Comment by hakib** [comment]
Hey @thany, 

I wouldn't want to give up browser support for something like escaping a string. As long as we depend on angular versions that support browsers all the way back to IE9 we should make an effort to maintain support for the library as well.

**Can you try to come up with a solution without using ES6?**

I haven't had any problems with other minifiers... is it only happening for you when using babli?

**Comment by thany** [comment]
I'm not sure if it's a bug in babili or not. But the nested escaping looks weird enough to make mistakes either way. You shouldn't want to have that in your code.

As for your ES6 remark, I can be short about that: no. Every browser supports template strings, except browsers that noone uses.

**Comment by thany** [comment]
Also if someone needs to support a fossilized browser for some reason, they can use an ES6 to ES5 cispiler for that.

At least that's my take on things, when I build components.
