### ISSUE TITLE
Select first item when return key is pressed

### ISSUE THREAD

**Issue by byounathan** [hakib/MassAutocomplete#74]
Is it possible to select the first item in the list when return key is pressed?

**Comment by hakib** [comment]
Yes, you can set `auto_select_first` in the ac-options to True and the first option will be selected automatically. 

Check out the [options section in the gh-pages](http://hakib.github.io/MassAutocomplete/)

**Comment by byounathan** [comment]
I have already tried that option. It is different from what I am asking for. Instead of automatically selecting the first option after blur, I want the selection to occur when the user **presses the return key**.

**Comment by hakib** [comment]
Oh, sorry... I missed this subtle difference. There is no built-in way of doing it right now.

**Comment by byounathan** [comment]
No worries, is this something that can be easily added?

**Comment by hakib** [comment]
I'm not sure you will be able to do it without forking this directive. Take a look at [this section](https://github.com/hakib/MassAutocomplete/blob/master/massautocomplete.js#L359) for the keyboard handling.
