### ISSUE TITLE
last_selected_value is never cleared

### ISSUE THREAD

**Issue by ncomont** [hakib/MassAutocomplete#78]
Hi,

We use `angular-mass-autocomplete` in our projects, and we're facing an issue with the `last_selected_value` property. I guess, I'm not the first to create an issue about that, so I'll try to explain the why : 

When I type `a` in the input, then `a` is stored as `last_selected_value`. I select an item, I clear the input, and the next time, I search for the same value. At this moment, the `nv === last_selected_value` returns in the `value`'s watcher, and my input is not taken in account. There is a little gif showing my issue : 

![issue_a](https://user-images.githubusercontent.com/26482371/34938413-8e11d8ac-f9e8-11e7-82f3-e60c6d86d95b.gif)

I understand why you put this condition in the watcher, but in my opinion, `last_selected_value` should be cleared in the `clear_selection()` function : 

```javascript
diff --git a/massautocomplete.js b/massautocomplete.js
index edfbae0..b53035c 100644
--- a/massautocomplete.js
+++ b/massautocomplete.js
@@ -303,6 +303,7 @@ angular.module('MassAutoComplete', [])
       function clear_selection() {
         $scope.selected_index = -1;
         $scope.container[0].removeAttribute('aria-activedescendant');
+        last_selected_value = undefined;
       }

```

I made this PR : https://github.com/hakib/MassAutocomplete/pull/79

Thanks,

**Comment by hakib** [comment]
Hey @ncomont, thanks for the PR. What you describe makes sense and I am able to reproduce.
