### ISSUE TITLE
How to select first value of options when focus is blurred or in on_detach method because i am getting here only the value not object of option ?

### ISSUE THREAD

**Issue by kritansh** [hakib/MassAutocomplete#80]

**Comment by hakib** [comment]
Hey @kritansh, I'm not sure I understand what you are trying to do. Can you setup a fiddle / codepen / plunker with an example of you are trying to achieve?

**Comment by kritansh** [comment]
Hi @hakib, Sorry for delay in replay, This is my plunker example [https://plnkr.co/edit/uudMXk9f9ySM7FnsEO0H?p=preview](url), Please look in to on_detach method when 
> auto_select_first = true
Actually here i want to auto select first item of autocomplete option when selection is void and action is blurred. Could you suggest me how can i get object  just like in on_select function when option is selected, into on_detach method so that i can fulfill my requirement. I looked into your code where you are only passing value to on_detach method.

**Comment by hakib** [comment]
Hey @kritansh,

In the `on_detach` hook you are getting the value of the model (not the object).

- If you need the last selected value you can use the last value sent to `on_select`. In you plunker you got this at `$scope.value`.
- If for some reason you need to rely on the value sent to `on_detach` you can search the suggestion list for the object with that value.

Hope this helps :)

**Comment by kritansh** [comment]
thanks @hakib
